---

- name: Creating repository in centos
  template:
      src:  create_nginx_repo.yml.j2
      dest: /etc/yum.repos.d/ngix.repo
  when: ansible_distribution == 'CentOS'
- package:
    name: "{{ nginx_packages }}"
    state: present
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

...
   
