---
# tasks file for ansible-nginx-role
- name: Install Nginx
  import_tasks: install.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian' 

- name: Configure Nginx
  import_tasks: configure.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian' 

- name: Configure Nginx
  import_tasks: status.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

